import type { Metadata } from 'next'
import { Poppins, Work_Sans as WorkSans } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})
const workSans = WorkSans({ subsets: ['latin'], variable: '--font-work-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${workSans.variable} ${poppins.variable}`}>
      <body>
        <main className="bg-slate-300/20">{children}</main>
      </body>
    </html>
  )
}
